[package]
name = "global-powers"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
strum = "0.26.3"
strum_macros = "0.26.4"
log = "0.4.22"
num-format = "0.4.4"
chrono = "0.4.38"